package com.google.ratel.service.classdata;

import java.util.*;
import java.util.Map;
import javax.servlet.ServletContext;
import com.google.ratel.util.ClassFinder;
import com.google.ratel.util.RatelUtils;
import com.google.ratel.deps.lang3.StringUtils;
import com.google.ratel.core.RatelService;

public class ClassDataService {

    private Map<String, ClassData> serviceByPathMap;

    private ServletContext servletContext;

    private List<String> packageNames;

    public ClassDataService(ServletContext servletContext, List<String> packageNames) {
        this.packageNames = packageNames;
        this.servletContext = servletContext;
    }

    public Map<String, ClassData> getAllServiceClassData() {
        // TODO add the data to the runtime
        if (serviceByPathMap == null) {
            Map tempClassDataMap = new HashMap<String, ClassData>();
            
            // TODO retrieve data from file that was generated by ANT. This is for environments where WAR is not unpacked

            ClassFinder finder = new ClassFinder(servletContext, RatelService.class, packageNames);
            Set<Class> classes = finder.getClasses();
            for (Class serviceClass : classes) {
                String serviceName = serviceClass.getName();

                for (String packageName : packageNames) {
                    int origLength = serviceName.length();
                    serviceName = StringUtils.remove(serviceName, packageName);
                    if (serviceName.length() != origLength) {
                        break;
                    }
                }
                
                //serviceName = StringUtils.removeStart(serviceName, ".");
                String servicePath = serviceName.replace(".", "/");
                ClassData classData = new ClassData();
                classData.setServiceClass(serviceClass);
                classData.setServicePath(servicePath);
                
                RatelUtils.populateMethods(classData);

                tempClassDataMap.put(servicePath, classData);
            }

            serviceByPathMap = tempClassDataMap;
        }
        return serviceByPathMap;
    }
}
