package com.google.ratel.service.classdata;

import com.google.ratel.*;
import java.util.*;
import java.util.Map;
import javax.servlet.ServletContext;
import com.google.ratel.util.ClassPathScanner;
import com.google.ratel.util.RatelUtils;
import com.google.ratel.deps.lang3.StringUtils;
import com.google.ratel.core.RatelService;

public class ClassDataService {

    protected Map<String, ClassData> serviceByPathMap;

    protected ServletContext servletContext;
    
    protected RatelConfig ratelConfig;

    protected List<String> packageNames;

    public ClassDataService(RatelConfig ratelConfig, List<String> packageNames) {
        this.packageNames = packageNames;
        this.ratelConfig = ratelConfig;
        this.servletContext = ratelConfig.getServletContext();
    }

    public Map<String, ClassData> getAllServiceClassData() {
        // TODO add the data to the runtime
        if (serviceByPathMap == null) {
            Map tempClassDataMap = new HashMap<String, ClassData>();
            
            // TODO retrieve data from file that was generated by ANT. This is for environments where WAR is not unpacked

            ClassPathScanner scanner = new ClassPathScanner(servletContext, RatelService.class, packageNames);
            Set<Class> classes = scanner.scan();
            for (Class serviceClass : classes) {
                String serviceName = serviceClass.getName();

                for (String packageName : packageNames) {
                    int origLength = serviceName.length();
                    serviceName = StringUtils.remove(serviceName, packageName);
                    if (serviceName.length() != origLength) {
                        break;
                    }
                }

                String servicePath = serviceName.replace(".", "/");
                if (!servicePath.startsWith("/")) {
                    servicePath = "/" + servicePath;
                }
                ClassData classData = new ClassData();
                classData.setServiceClass(serviceClass);
                classData.setServicePath(servicePath);
                
                RatelUtils.populateMethods(classData);

                if (ratelConfig.getLogService().isDebugEnabled()) {
                    String msg = servicePath + " -> " + serviceClass.getName();
                    ratelConfig.getLogService().debug(msg);
                }

                tempClassDataMap.put(servicePath, classData);
            }

            serviceByPathMap = tempClassDataMap;
        }
        return serviceByPathMap;
    }
}
